arch: amd64
os: linux
dist: bionic

language: node_js

node_js:
  - 14

addons:
  apt:
    packages:
      # Cypress
      - libgconf-2-4

branches:
  only:
    - master

cache:
  npm: true
  directories:
    # Cypress
    - ~/.cache
  override:
    - npm ci
    - npm run cy:verify
    - npm run cy:info

install:
  - npm ci

script: npm run prettify-check &&
  npm run stylelint &&
  npm run lint &&
  npm run test &&
  npx start-server-and-test start http://localhost:3000 test-e2e
